  name: myapp
  description: A new Flutter project.
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: '>=2.19.6 <3.0.0'

  dependencies:
    flutter:
      sdk: flutter
    firebase_core: ^2.10.0
    cloud_firestore: ^4.17.5
    firebase_database: ^10.0.0
    fl_chart: ^0.40.0
    intl: ^0.17.0
    http: ^0.13.6
    cupertino_icons: ^1.0.2
    xml: ^6.2.2
    collection: ^1.16.0
    flutter_dotenv: ^5.0.2


  dev_dependencies:
    flutter_launcher_icons: ^0.9.2
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true
